name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
      - uses: Swatinem/rust-cache@v2
      - name: install deps
        # https://github.com/emilk/egui/blob/6ae4bc486b2608212f5fc8453f5aa7e5106853f8/.github/workflows/rust.yml#L26
        # https://github.com/robbert-vdh/nih-plug/blob/78c84b75962af61393e67dabb122b28d2e968625/.github/workflows/build.yml#L40
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libgl-dev libjack-dev libxcb1-dev libxcb-icccm4-dev libxcursor-dev libxkbcommon-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-xcb-dev libxcb-dri2-dev
      - run: cargo fmt --all --check
      - run: cargo build
