# based on https://github.com/emilk/egui/blob/6ae4bc486b2608212f5fc8453f5aa7e5106853f8/.github/workflows/rust.yml
name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
      - uses: Swatinem/rust-cache@v2
      - name: install deps
        run: sudo apt-get update && sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev
      - run: cargo fmt --all --check
      - run: cargo build
